""" Search strategy planner

This script is the entry point of the search strategy planning.

* Calls the correct search strategy function so it can be thought of
  as a dispatcher.

Public functions:
    * get_search_plan - returns search plan generated by the specified algorithm
"""

from scipy.special import comb
from argparse import ArgumentParser
from fuzzer.common import file_reader as fr
from fuzzer.controllers import search_strategies as strategies
import json


class SearchPlan:
    def __init__(self, depth: int, nets: list):
        self.depth = depth
        self.nets = nets
        self.verify_input()

    def get_search_plan(self, algo: str) -> list:
        """ Function that calls the correct search algorithm """
        if algo == "bfs":
            search_plan = strategies.bfs(self.depth, self.nets)
        else:
            raise ValueError("Unknown search algorithm {}".format(algo))

        return search_plan

    def get_fuzzing_stats(self) -> dict:
        stats = {}
        total = 0
        N = len(self.nets)

        for k in range(1, self.depth + 1):
            num_combs = comb(N, k, exact=True)
            depth_key = "depth{}".format(k)
            stats.update({depth_key: num_combs})
            total += num_combs

        stats.update({"total": total})

        return stats

    # @Tested
    def verify_input(self):
        """ Function that collects all checks on the class input """
        verify_depth(self.depth, self.nets)


# @Tested composite
def verify_depth(depth: int, nets: list):
    """ Verify depth is not greater than the number of elements in the list
    In that case the underlying combinations algorithm would just give
    all combinations as if (depth == len(nets)) but we choose to raise
    an exception as this is likely indicative of an error somewhere
    """
    if depth > len(nets):
        raise ValueError("Depth is higher than number of nets")


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument("-d", "--depth", dest="depth",
                        help="The max depth we are checking for failed links")
    parser.add_argument("-a", "--algo", dest="algo",
                        help="Search algorithm to use")
    args = parser.parse_args()

    if not (args.depth and args.algo):
        raise ValueError("Forgot to specify search depth or algorithm")

    nets = fr.get_networks()

    planner = SearchPlan(int(args.depth), nets)
    search_plan = planner.get_search_plan(args.algo)
    stats = planner.get_fuzzing_stats()

    for s in search_plan:
        print(s)

    print(json.dumps(stats, indent=4))
